In [1]:
import pandas as pd

In [ ]:
train_prev = pd.read_csv('data/train_prev_new.csv')

In [15]:
train_prev.insert(0, 'id', range(len(train_prev)))

In [16]:
train_prev

,id,pressure,maxtemp,temparature,mintemp,dewpoint,humidity,cloud,sunshine,windspeed,...,avg3_windspeed_minus_cloud,avg3_cloud_windspeed_times,avg3_cloud_div_windspeed,avg3_windspeed_div_cloud,avg3_sunshine_windspeed_plus,avg3_sunshine_minus_windspeed,avg3_windspeed_minus_sunshine,avg3_sunshine_windspeed_times,avg3_sunshine_div_windspeed,avg3_windspeed_div_sunshine
0,0,1013.4,18.1,17.8,16.9,16.8,95.0,95.0,0.0,35.6,...,-56.3,1452.4,4.0,0.3,22.2,-15.9,15.9,56.4,0.2,5.9
1,1,1021.8,21.3,18.4,15.2,9.6,52.0,45.0,3.6,24.8,...,-52.5,2075.2,3.1,0.3,28.0,-22.4,22.4,50.1,0.2,0.7
2,2,1022.7,20.6,18.6,16.5,12.5,79.0,81.0,0.0,15.7,...,-36.2,1782.9,2.4,0.4,30.1,-22.2,22.2,79.8,0.2,3.0
3,3,1022.8,19.5,18.4,15.3,11.3,56.0,46.0,7.6,28.4,...,-48.3,1923.2,3.2,0.4,26.6,-24.2,24.2,29.8,0.0,2.3
4,4,1019.7,15.8,13.6,12.7,11.8,96.0,100.0,0.0,52.8,...,-34.4,1231.4,2.9,0.5,26.7,-19.2,19.2,101.7,0.1,3.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2182,2182,1014.6,23.2,20.6,19.1,19.9,97.0,88.0,0.1,22.1,...,-55.7,2677.3,2.9,0.4,32.2,-29.8,29.8,41.0,0.0,11.5
2183,2183,1012.4,17.2,17.3,16.3,15.3,91.0,88.0,0.0,35.3,...,-56.4,2609.9,3.0,0.4,31.1,-29.4,29.4,31.1,0.0,78.9
2184,2184,1013.3,19.0,16.3,14.3,12.6,79.0,79.0,5.0,32.9,...,-58.7,2581.3,3.1,0.3,29.4,-29.3,29.3,0.7,0.0,73.7
2185,2185,1022.3,16.4,15.2,13.8,14.7,92.0,93.0,0.1,18.0,...,-54.9,2550.1,3.0,0.4,31.8,-28.4,28.4,55.6,0.1,75.9
2186,2186,1013.8,21.2,19.1,18.0,18.0,89.0,88.0,1.0,48.0,...,-57.9,2459.8,3.4,0.3,30.4,-27.0,27.0,55.4,0.1,62.2

In [5]:
def split_train_validation(data, validation_ratio=0.2):
    """
    Splits the data into training and validation sets according to the specified validation_ratio.
    The last X% of rows are assigned to the validation set.
    
    Parameters:
        data (pd.DataFrame): the full dataset
        validation_ratio (float): the proportion of data to use for validation (default is 0.2)

    Returns:
        train_data (pd.DataFrame), val_data (pd.DataFrame)
    """
    split_index = int((1 - validation_ratio) * len(data))
    train_data = data.iloc[:split_index]
    val_data = data.iloc[split_index:]
    return train_data, val_data

In [17]:
train, val = split_train_validation(train_prev, validation_ratio=0.2)

In [18]:
train

,id,pressure,maxtemp,temparature,mintemp,dewpoint,humidity,cloud,sunshine,windspeed,...,avg3_windspeed_minus_cloud,avg3_cloud_windspeed_times,avg3_cloud_div_windspeed,avg3_windspeed_div_cloud,avg3_sunshine_windspeed_plus,avg3_sunshine_minus_windspeed,avg3_windspeed_minus_sunshine,avg3_sunshine_windspeed_times,avg3_sunshine_div_windspeed,avg3_windspeed_div_sunshine
0,0,1013.4,18.1,17.8,16.9,16.8,95.0,95.0,0.0,35.6,...,-56.3,1452.4,4.0,0.3,22.2,-15.9,15.9,56.4,0.2,5.9
1,1,1021.8,21.3,18.4,15.2,9.6,52.0,45.0,3.6,24.8,...,-52.5,2075.2,3.1,0.3,28.0,-22.4,22.4,50.1,0.2,0.7
2,2,1022.7,20.6,18.6,16.5,12.5,79.0,81.0,0.0,15.7,...,-36.2,1782.9,2.4,0.4,30.1,-22.2,22.2,79.8,0.2,3.0
3,3,1022.8,19.5,18.4,15.3,11.3,56.0,46.0,7.6,28.4,...,-48.3,1923.2,3.2,0.4,26.6,-24.2,24.2,29.8,0.0,2.3
4,4,1019.7,15.8,13.6,12.7,11.8,96.0,100.0,0.0,52.8,...,-34.4,1231.4,2.9,0.5,26.7,-19.2,19.2,101.7,0.1,3.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1744,1744,1014.1,28.2,24.1,22.5,20.8,83.0,71.0,6.8,22.0,...,-41.2,1828.5,3.0,0.5,32.1,-24.2,24.2,137.0,0.1,10.2
1745,1745,1014.9,25.3,23.3,22.3,20.4,78.0,80.0,1.0,29.7,...,-41.2,1595.1,3.2,0.4,31.0,-20.6,20.6,157.9,0.2,8.1
1746,1746,1015.0,27.1,24.5,21.0,21.6,81.0,81.0,3.5,13.2,...,-54.8,1742.0,3.7,0.3,25.5,-19.6,19.6,65.1,0.1,16.3
1747,1747,1017.7,27.7,25.9,23.4,21.1,81.0,86.0,2.5,24.5,...,-55.7,1669.1,4.0,0.3,25.4,-17.9,17.9,75.2,0.2,12.2
1748,1748,1013.0,30.2,26.3,24.2,21.8,83.0,84.0,3.1,14.5,...,-59.9,1850.7,4.1,0.3,24.8,-20.1,20.1,45.7,0.1,14.4

In [19]:
val

,id,pressure,maxtemp,temparature,mintemp,dewpoint,humidity,cloud,sunshine,windspeed,...,avg3_windspeed_minus_cloud,avg3_cloud_windspeed_times,avg3_cloud_div_windspeed,avg3_windspeed_div_cloud,avg3_sunshine_windspeed_plus,avg3_sunshine_minus_windspeed,avg3_windspeed_minus_sunshine,avg3_sunshine_windspeed_times,avg3_sunshine_div_windspeed,avg3_windspeed_div_sunshine
1749,1749,1010.3,30.6,27.0,25.5,23.4,84.0,58.0,7.7,14.8,...,-66.3,1464.7,5.1,0.2,20.4,-14.4,14.4,50.8,0.2,6.1
1750,1750,1012.5,26.7,24.5,23.7,22.6,77.0,84.0,3.5,22.0,...,-58.1,1394.5,4.4,0.2,22.4,-13.5,13.5,73.4,0.3,5.5
1751,1751,1018.1,26.8,24.5,23.1,22.2,82.0,81.0,1.6,26.7,...,-58.2,1308.1,4.5,0.2,21.9,-12.3,12.3,78.6,0.3,4.3
1752,1752,1016.8,26.0,24.8,23.7,21.4,85.0,83.0,0.0,31.7,...,-53.2,1623.0,3.6,0.3,25.4,-16.9,16.9,77.9,0.2,8.3
1753,1753,1017.2,28.9,25.2,23.7,19.1,87.0,82.0,2.0,16.2,...,-55.9,2213.9,3.2,0.3,28.5,-25.1,25.1,39.9,0.1,7.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2182,2182,1014.6,23.2,20.6,19.1,19.9,97.0,88.0,0.1,22.1,...,-55.7,2677.3,2.9,0.4,32.2,-29.8,29.8,41.0,0.0,11.5
2183,2183,1012.4,17.2,17.3,16.3,15.3,91.0,88.0,0.0,35.3,...,-56.4,2609.9,3.0,0.4,31.1,-29.4,29.4,31.1,0.0,78.9
2184,2184,1013.3,19.0,16.3,14.3,12.6,79.0,79.0,5.0,32.9,...,-58.7,2581.3,3.1,0.3,29.4,-29.3,29.3,0.7,0.0,73.7
2185,2185,1022.3,16.4,15.2,13.8,14.7,92.0,93.0,0.1,18.0,...,-54.9,2550.1,3.0,0.4,31.8,-28.4,28.4,55.6,0.1,75.9
2186,2186,1013.8,21.2,19.1,18.0,18.0,89.0,88.0,1.0,48.0,...,-57.9,2459.8,3.4,0.3,30.4,-27.0,27.0,55.4,0.1,62.2

In [20]:
train.drop(['id'], axis=1, inplace=True)
val.drop(['id'], axis=1, inplace=True)

C:\Users\Ola\AppData\Local\Temp\ipykernel_66364\2720518800.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train.drop(['id'], axis=1, inplace=True)
C:\Users\Ola\AppData\Local\Temp\ipykernel_66364\2720518800.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  val.drop(['id'], axis=1, inplace=True)

In [21]:
X_train = train.drop('rainfall', axis=1)
Y_train = train['rainfall']
X_valid = val.drop('rainfall', axis=1)
Y_valid = val['rainfall']

In [ ]:
# X_train.to_csv('../data/X_train_new.csv', index=False)
# Y_train.to_csv('../data/Y_train_new.csv', index=False)
# X_valid.to_csv('../data/X_valid_new.csv', index=False)
# Y_valid.to_csv('../data/Y_valid_new.csv', index=False)